# Generated by Django 3.0.5 on 2020-05-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_auto_20200520_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default=None, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
