# Generated by Django 3.0.5 on 2020-05-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0007_auto_20200521_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
