# Generated by Django 3.0.5 on 2020-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0009_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, height_field='height_field', upload_to='company_images', width_field='width_field'),
        ),
    ]
